config/routes.rb
Rails.application.routes.draw do
  get 'hospitals/index'
  get 'hospitals/show'
  post 'pages/home'

  get '/tagged', to: "hospitals#tagged", as: :tagged
  # delete '/tagged', to: "hospitals#taggeddestroy", as: :tagged_destroy

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hospitals, only: [:index, :show, :new, :create] do
    get '/upsave' => 'hospitals#upsave'
    get '/downsave' => 'hospitals#downsave'
    resources :comments, only: [:show, :new, :create]
  end
  get '/users/dashboard', to: 'pages#dashboard'
  get '/users/profile', to: 'users#show'
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  acts_as_commentable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

end

app/controllers/comments_controller.rb
# comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def show
    set_hospital
    @comments = Comment.all
  end

  def new
    # creating new comment - shown to user only if logged in
    commentable = set_hospital
    @comment = Comment.new
    commentable.comment = @comment
  end

  def create
    set_hospital
    @comment = Comment.new(comment_params)
    @comment.commentable = @hospital
    @comment.user = current_user
    @comment.avg_rating = (@comment.doctor_rating + @comment.service_rating + @comment.environment_rating + @comment.price_rating) / 4
    @comment.save
    hospitals = Hospital.all
    sum = 0
    @hospital.comments.each do | comment |
      sum += comment.avg_rating || 0
    end
    @hospital.rating = sum / @hospital.comments.count
    @hospital.save
    redirect_to hospital_path(@hospital)
  end

  private

  def set_hospital
    @hospital = Hospital.find(params[:hospital_id])
  end

  def comment_params
    params.require(:comment).permit(:title, :comment, :doctor_rating, :service_rating, :environment_rating, :price_rating)
  end

  def location_filter
    @hospitals = Hospital.where("city ILIKE ?", "%#{params[:city]}%")
  end
end

app/views/comments/_new.html.erb
<!-- comments/show.html.erb -->
<% if user_signed_in? %>
  <div class="rating-comment">
    <!-- <input id="input-id" type="text" class="rating" data-size="lg" > -->
    <%= form_for Comment.new, url: hospital_comments_path(@hospital) do |f|%>
      <div class="ratings-container">
        <table>
          <tr>
            <td class="left-column">Doctor</td>
            <td><input id="doctor_rating" name="comment[doctor_rating]" class="rating rating-loading" data-min="0" data-max="5" data-step="0.1" value="2" data-size="sm"></td>
          </tr>
          <tr>
            <td class="left-column">Service</td>
            <td><input id="service_rating" name="comment[service_rating]" class="rating rating-loading" data-min="0" data-max="5" data-step="0.1" value="2" data-size="sm"></td>
          </tr>
          <tr>
            <td class="left-column">Environment</td>
            <td><input id="environment_rating" name="comment[environment_rating]" class="rating rating-loading" data-min="0" data-max="5" data-step="0.1" value="2" data-size="sm"></td>
          </tr>
          <tr>
            <td class="left-column">Price</td>
            <td><input id="price_rating" name="comment[price_rating]" class="rating rating-loading" data-min="0" data-max="5" data-step="0.1" value="2" data-size="sm"></td>
          </tr>
        </table>
      </div>
      <br>
      <!-- <label for="comment_title">Title</label>
    <input id="comment_title" class="form-control" name="comment[title]" type="text"> -->
      <div class="commentbox">
        <label for="comment_comment">Comment</label>
        <input id="comment_comment" class="form-control" name="comment[comment]" type="text">
        <input class="btn btn-primary review-button" type="submit" value="Create comment">
      </div>
    <% end %>
  </div>
<% end %>