config/routes.rb
Rails.application.routes.draw do
  get 'hospitals/index'
  get 'hospitals/show'
  post 'pages/home'

  get '/tagged', to: "hospitals#tagged", as: :tagged
  # delete '/tagged', to: "hospitals#taggeddestroy", as: :tagged_destroy

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hospitals, only: [:index, :show, :new, :create] do
    get '/upsave' => 'hospitals#upsave'
    get '/downsave' => 'hospitals#downsave'
    resources :comments, only: [:show, :new, :create]
  end
  get '/users/dashboard', to: 'pages#dashboard'
  get '/users/profile', to: 'users#show'
end

app/views/shared/_dropdown.html.erb
<div class="btn-group" id="anchored">
  <button type="button" class="btn btn-primary dropdown-toggle filterbutton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Insurer
  </button>
  <div class="dropdown-menu">
    <% @insurers.each do |insurer| %>
      <a class="dropdown-item" href="<%= hospitals_path(@hospital, city: params[:city],tag: tags(insurer), anchor: "anchored") %>"><%= insurer%></a>
    <% end %>
  </div>
</div>
<% if params["city"].present? %>
  <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle filterbutton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      District
    </button>
    <div class="dropdown-menu">
      <% @districts.uniq.each do |district| %>
        <a class="dropdown-item" href="<%= hospitals_path(@hospital, city: params[:city], tag: tags(district), anchor: "anchored")%>"><%= district %></a>
      <% end %>
    </div>
  </div>
<% end %>
<div class="btn-group">
  <button type="button" class="btn btn-primary dropdown-toggle filterbutton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Provider Type
  </button>
  <div class="dropdown-menu">
    <% @provider_types.each do |type| %>
      <a class="dropdown-item" href="<%= hospitals_path(@hospital, city: params[:city], tag: tags(type), anchor: "anchored")%>"><%=  type%></a>
    <% end %>
  </div>
</div>
<div class="btn-group">
  <button type="button" class="btn btn-primary dropdown-toggle filterbutton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Language
  </button>
  <div class="dropdown-menu">
    <% @languages.each do |language| %>
      <a class="dropdown-item" href="<%= hospitals_path(@hospital, city: params[:city], tag: tags(language), anchor: "anchored")%>"><%= language %></a>
    <% end %>
  </div>
</div>
<div class="btn-group">
  <button type="button" class="btn btn-primary dropdown-toggle filterbutton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Specialty
  </button>
  <div class="dropdown-menu scroll">
    <% @specialties.each do |specialty| %>
      <a class="dropdown-item" href="<%= hospitals_path(@hospital, anchor: "anchored", city: params[:city], tag: tags(specialty.split(' ').first))%>"><%= specialty %></a>
    <% end %>
  </div>
</div>
<div>
  <% unless params[:city] == "" || params[:city].nil? %>
    <p class='search-loc'>Search Location:  <%= params[:city] %></p>
  <% end %>
</div>
<div class="filtertags">
  <% if !params[:tag].nil? && params[:query] != "" %>
    <% params[:tag].delete_at(0) if params[:tag][0] == "" %>
    <% (params[:tag] || []).each do |tag| %>
      <%= link_to tag, hospitals_path(@hospital, tag: tag), class: "tag"%>
    <% end %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website was made with <i class="fas fa-heart"></i>  <br>
     by the Dream Team
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalTitle">Show Your Driver!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <h6>目的地</h6>
          <p>
            <pre id="markup"><%=@hospital.cn_address%></pre>
          </p>
        </div>
        <br>
        <div>
          <h6>Destination</h6>
          <p><%= @hospital.address %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo2.jpg", class: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= form_tag hospitals_index_path, method: :get, class: "search" do %>
        <!-- <input class="type"> -->
        <i class="fa fa-search"></i>
        <%= text_field_tag :query, params[:query], class: "form-control-search"%>
      <% end %>
    </ul>
    <% if user_signed_in? %>
      <ul class="navbar-nav">
        <li id="welcome">  Welcome <%= current_user.first_name%><%= current_user.last_name%>!</li>
        <li class="avatar" style="margin-right: 10px">
          <%= link_to "Saved", users_dashboard_path(@user), class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav ml-auto">
        <li class="login">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link", id: "signup" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>
<hr class="line-nav">