config/routes.rb
Rails.application.routes.draw do
  get 'hospitals/index'
  get 'hospitals/show'
  post 'pages/home'

  get '/tagged', to: "hospitals#tagged", as: :tagged
  # delete '/tagged', to: "hospitals#taggeddestroy", as: :tagged_destroy

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hospitals, only: [:index, :show, :new, :create] do
    get '/upsave' => 'hospitals#upsave'
    get '/downsave' => 'hospitals#downsave'
    resources :comments, only: [:show, :new, :create]
  end
  get '/users/dashboard', to: 'pages#dashboard'
  get '/users/profile', to: 'users#show'
end

app/views/pages/dashboard.html.erb
<div class="container">
  <h1 class="profile">Saved</h1>
  <hr class="dashboard-line">
  <div class="main">
    <div class="cards">
      <% @saves.each do |hospital| %>
        <!-- <div class="col-xs-12 col-sm-6 col-md-4"> -->
        <div class="card" >
          <%#= cl_image_tag hospital.image, class: "card-img" %>
          <div class="card-description">
            <%= cl_image_tag((hospital.name.parameterize.underscore + ".jpg"), :class => "card-img") %>
            <div> Rating: <% (hospital.rating || 0).round(0).to_i.times do%>
                <i class="fas fa-star star"></i>
              <% end %>
            </div>
            <p id="name"><%= hospital.name%></p>
            <hr>
            <div class="time-price">
              <div>
                <p id="index-district"><i class="fas fa-map-pin"></i> <%= hospital.district %></p>
              </div>
            </div>
            <hr>
            <div class="info-under-line">
              <p id="index-address"><%=hospital.address%></p>
              <p id="provider-type"><%= hospital.provider_type %></p>
            </div>
            <%= link_to "", hospital_path(hospital), class: 'card-link' %>
          </div>
        </div>
        <!-- </div> -->
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="full">
  <div id="moving-container">
    <img src="https://images.pexels.com/photos/574282/pexels-photo-574282.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" height="42" width="42">
    <img src="https://images.pexels.com/photos/547114/pexels-photo-547114.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500" height="42" width="42">
    <img src="https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500" height="42" width="42">
    <img src="https://images.pexels.com/photos/1084188/pexels-photo-1084188.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500" height="42" width="42">
  </div>
  <div class="container">
    <div class="home-row">
      <div class="col-auto">
        <h2 class="home-tagline">Find a hospital in a matter of seconds
          <div id="time"></div>
        </h2>
      </div>
      <form action='<%= hospitals_index_path %>' method='GET' class="home-form">
        <!--    <div class="form-row"> -->
        <div class="col-auto">
          <p class="home-form">CITY</p>
          <input type="text" class="form-control" name="city">
        </div>
        <!--       <div class="col">
            <input type="text" class="form-control" placeholder="Specialty">
          </div> -->
        <div class="col-auto">
          <p class="home-form">HEALTH INSURER</p>
          <input list="health insurers" class="form-control" name="tag[]">
          <datalist id="health insurers">
            <option value="CIGNA">
              <option value="MSH">
              </datalist>
            </div>
            <!-- <div class="col-auto">
            <div class="form-check mb-2">
              <input class="form-check-input" type="checkbox" id="autoSizingCheck">
              <label class="form-check-label" for="autoSizingCheck">
                English?
              </label>
            </div>
          </div> -->
            <div class="col-auto">
              <button type="submit" class="btn btn-primary btn-lg btn-block">Search Hospital</button>
            </div>
            <!--    </div> -->
          </form>
        </div>
      </div>
    </div>