config/routes.rb
Rails.application.routes.draw do
  get 'hospitals/index'
  get 'hospitals/show'
  post 'pages/home'

  get '/tagged', to: "hospitals#tagged", as: :tagged
  # delete '/tagged', to: "hospitals#taggeddestroy", as: :tagged_destroy

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hospitals, only: [:index, :show, :new, :create] do
    get '/upsave' => 'hospitals#upsave'
    get '/downsave' => 'hospitals#downsave'
    resources :comments, only: [:show, :new, :create]
  end
  get '/users/dashboard', to: 'pages#dashboard'
  get '/users/profile', to: 'users#show'
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :reviews
  has_many :appointments

  # validates :image
  # validates :name, presence: true, uniqueness: true
  # validates :address, presence: true, uniqueness: true
  # validates :open_at, presence: true
  # validates :close_at, presence: true
  # validates :longitude, presence: true
  # validates :latitude, presence: true
  # validates :tel, presence: true, uniqueness: true

  acts_as_commentable
  acts_as_taggable_on :tags

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  acts_as_saveable
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_hospital, only: [:show, :upsave]

  def index
    @insurers = ["CIGNA", "MSH"]
    # "Allianz", "AXA PPP", "AXA ICBC", "AXA Tianping", "BUPA"
    @provider_types = ["Private", "Public", "Dental", "Wellness Checkup"]
    @languages = ["Cn", "Eng", "Canto", "Fr", "Span", "Ru", "Jp", "Kr", "Ger", "Farsi", "Dutch", "Filipino"]
    @specialties = ["Acupuncture", "Cardiology", "Dental", "Dental Care", "Ear, Nose & Throat", "Endocrinology", "Gastroenterology", "General Medicine", "General Surgery", "Gynecology", "Haematology", "Infectious Disease", "Internal Medicine", "Kidney Disease", "Liver Disease", "Neurology", "Nuclear Medicine", "OB & GYN", "Ophthalmology", "Organ Transplants", "Orthopaedics", "Osteology", "Pediatrics", "Physical Checkup", "Pneumology", "Respiratory", "Rheumatology", "Sarcoidosis", "Sport Medicine", "Traditional Chinese Medicine", "TCM physiotherapy", "Tumors", "Urology"]
    @districts = []
    @hospitals = Hospital.all

    if (params[:tag] == [""] && params["city"] != "")
      location_filter
    elsif (params[:tag] != [""] && params["city"].present?) || (params[:tag] != [""] && params["city"] == "")
      location_filter
      @hospitals = @hospitals.tagged_with(params[:tag])
    end

    # @hospitals = @hospitals.tagged_with(params[:tag])
    # elsif !params[:tag] && !params["city"].present?
    #   @hospitals
    # else
    #   location_filter
    #   @hospitals = @hospitals.tagged_with(params[:tag])
    #   # raise

    #district
    @district_hospitals = Hospital.where(city: params["city"])
    @district_hospitals.all.each do |hospital|
      @districts << hospital.district
    end

    # search bar
    if params[:query].present?
      return @hospitals = Hospital.where("name @@ ?", "%#{params[:query]}%")
    end

    set_markers

  end

  def show
    # displaying comments
    @comment = Comment.new
    if user_signed_in?
      @saved = current_user.saved_up_on? @hospital
    else
      @saved = false
    end
    # mapbox
    @marker = {
      lat: @hospital.latitude,
      lng: @hospital.longitude
    }
  end

  # def show
  #   # displaying comments
  #   @comment = Comment.new
  #   @saved = @hospital.saves_for.empty? ? false : @hospital.saves_for.first.save_flag
  #   # mapbox
  #   @marker = {
  #     lat: @hospital.latitude,
  #     lng: @hospital.longitude
  #   }
  # end


  def upsave
    @saved =current_user.saved_up_on? @hospital
    if !@saved
      @hospital.upsaved_by current_user
    else
      @hospital.downsave_from current_user
    end
    redirect_to hospital_path(@hospital)
  end

  def downsave
    @hospital.downsave_from current_user
    redirect_to hospital_path(@hospital)
  end

  # def specialty_list
  #   temp = []
  #   @hospitals = Hospital.all
  #   @hospitals.each do |hospital|
  #     hospital.specialty.split(", ").each do |specialty|
  #       temp << specialty
  #     end
  #   end
  #   print @specialties = temp.uniq.sort
  # end

  # def taggeddestroy
  #   @hospital.find(params[:id]).type_list.remove(params[:tag])
  # end

  private

  def set_hospital
    @hospital = Hospital.find((params[:id] || params[:hospital_id]))
  end

  def set_markers
    @markers = @hospitals.map do |hospital|
      {
        lat: hospital.latitude,
        lng: hospital.longitude
      }
    end
  end

  def location_filter
    @hospitals = Hospital.where("city ILIKE ?", "%#{params[:city]}%")
  end
end

app/views/hospitals/index.html.erb
<div class="dropdown">
  <%= render 'shared/dropdown' %>
</div>
<div class="main">
  <div class="cards">
    <% @hospitals.each do |hospital| %>
      <!-- <div class="col-xs-12 col-sm-6 col-md-4"> -->
      <div class="card" >
        <%#= cl_image_tag hospital.image, class: "card-img" %>
        <div class="card-description">
          <%= cl_image_tag((hospital.name.parameterize.underscore + ".jpg"), :class => "card-img", :default_image => "hospital_placeholder.png") %>
          <div>
            <% if !hospital.rating.nil? and hospital.rating >= 1 %>
              Rating: <% (hospital.rating || 0).round(0).to_i.times do%>
                <i class="fas fa-star star"></i>
              <% end %>
            <% end %>
          </div>
          <p id="name"><%= hospital.name%></p>
          <hr>
          <div class="location">
            <div>
              <p id="index-district"><i class="fas fa-map-pin"></i> <%= hospital.district %></p>
            </div>
          </div>
          <hr>
          <div class="info-under-line">
            <p id="index-address"><%=hospital.address%></p>
            <p id="provider-type"><%= hospital.provider_type %></p>
          </div>
          <%= link_to "", hospital_path(hospital), class: 'card-link' %>
        </div>
      </div>
      <!-- </div> -->
    <% end %>
  </div>
  <!-- map styling in _card.scss -->
  <div class="card" id="map_index"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/hospitals/show.html.erb
<h1 class="name"><a class="clickable" href="<%= hospital_upsave_path(@hospital) %>"><i class="fas fa-heart <%= @saved ? 'red' : 'gray' %>"></i></a> <%= @hospital.name%> </h1>
<div class="show-container">
  <div class="show-row" style="height: 50%;">
    <div class="hospital col-sm">
      <div class="d-flex">
        <div class="description" >
          <div class="image-on-image">
            <div class="hospital-img"><%= cl_image_tag((@hospital.name.parameterize.underscore + ".jpg"), :class => "hospital-img", :default_image => "hospital_placeholder.png")%></div>
            <div class="taxi">
              <button type="link" data-toggle="modal" data-target="#exampleModalCenter" class='btn btn-primary'><i class="fas fa-taxi"></i> Taxi printout </button>
            </div>
          </div>
          <div class="tags">
            <% @hospital.tag_list.each do |tag| %>
              <div class="tag"><%= link_to tag, hospitals_path(@hospital, tag: tag) %></div>
            <% end %>
          </div>
          <div class="show-card-description">
            <!--   <div>
            <div class="show-description"> -->
            <% unless @hospital.tel == "n/a" || @hospital.tel.nil? %>
              <div class='static'><strong>Phone:</strong></div>
              <div class='from-db'>
                <p><%= @hospital.tel%> </p>
              </div>
            <% end %>
            <div class='static'><strong>Address:</strong></div>
            <div class='from-db'>
              <p><%= @hospital.address%> </p>
            </div>
            <div class='static'><strong>Working Hours:</strong></p>
          </div>
          <div class='from-db'><% if @hospital.weekday.include?("Monday" || "Tuesday" || "Wednesday" || "Thursday" || "Friday") %> <%= @hospital.weekday %>
            <% else %>
              <p class="time">Monday - Friday: <%= @hospital.weekday %> </p>
            <% end %>
            <% if @hospital.weekend.include?("Saturday" || "Sunday") %> <%= @hospital.weekend %>
            <% else %>
              <p class="time">Saturday and Sunday: <%= @hospital.weekend %></p>
              <br>
            <% end %></div>
          <div class='static'><strong>Specialties:</strong></div>
          <div class='from-db'><%= @hospital.specialty%></p>
        </div>
        <% unless @hospital.foreign_lang == "" %>
          <div class='static'><strong>Foreign Language Service:</strong></div>
          <div class='from-db'>
            <p><%= @hospital.foreign_lang%></p>
            <br>
          </div>
        <% end %>
        <% unless @hospital.website == "" || @hospital.website.nil? %>
          <div class='static'><strong>Website:</strong></div>
          <div class='from-db'><a href="//<%= @hospital.website %>"><%= @hospital.website%></a></div>
        <% end %>
      </div>
    </div>
    <div
  id="map"
  style="width: 180vh;"
  data-markers="<%= @marker.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>
<hr class="show-line">
<div class="review">
  <h2 class="comment">Reviews</h2>
  <div class="overall-rating">
    <% if !@hospital.rating.nil? and @hospital.rating >= 1 %>
      <div class="overall-rating-with-number">
        <div class="rating-description"> Overall rating: </div>
        <div class="rating-number">
          <%= @hospital.rating.round(1) %>
        </div>
      <% end %>
    </div>
  </div>
  <div class= "overflow">
    <% @hospital.comments.each do |comment| %>
      <div class="d-flex align-items-center">
        <i class="fas fa-poo-storm"></i>
        <p class="user-name"><%= comment.user.first_name.capitalize %>  <%= comment.user.last_name.capitalize %></p>
        <!--         Title: <%= comment.title %> <br> -->
      </div>
      <% (comment.avg_rating || 0).round(0).to_i.times do %>
        <i class="fas fa-star"></i>
      <% end %><br>
      <%= comment.comment %><br>
      <hr>
      <br>
    <% end %>
  </div>
  <%= render 'comments/new' %>
</div>
<!-- map -->
<%= render 'shared/modal'%>